"""empty message

Revision ID: 822ac0b94648
Revises: e99c5ea68a5a
Create Date: 2018-05-15 20:10:20.495679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822ac0b94648'
down_revision = 'e99c5ea68a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop_activity', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop_activity', 'active')
    # ### end Alembic commands ###
