"""initial setup

Revision ID: e42b1f40a3c5
Revises: 
Create Date: 2018-05-13 11:03:37.119414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42b1f40a3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('workshop_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('unit_is_year', sa.Boolean(), nullable=True),
    sa.Column('admin_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_owner'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_activity_date'), 'workshop_activity', ['date'], unique=False)
    op.create_table('post_it',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('year_timestamp', sa.Integer(), nullable=True),
    sa.Column('mdy_timestamp', sa.Date(), nullable=True),
    sa.Column('on_sex', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workshop_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_it_mdy_timestamp'), 'post_it', ['mdy_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_it_mdy_timestamp'), table_name='post_it')
    op.drop_table('post_it')
    op.drop_index(op.f('ix_workshop_activity_date'), table_name='workshop_activity')
    op.drop_table('workshop_activity')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
