"""empty message

Revision ID: e99c5ea68a5a
Revises: e42b1f40a3c5
Create Date: 2018-05-13 23:12:08.286251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c5ea68a5a'
down_revision = 'e42b1f40a3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop_activity', sa.Column('unique_str', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_workshop_activity_unique_str'), 'workshop_activity', ['unique_str'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_activity_unique_str'), table_name='workshop_activity')
    op.drop_column('workshop_activity', 'unique_str')
    # ### end Alembic commands ###
